 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package GUIPractice;

import java.awt.CardLayout;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.io.*;
//import java.time.temporal.WeekFields;
import java.util.*;

/**
 *
 * @author aburd
 */
public class AppOpen extends javax.swing.JFrame {

    boolean cellNameTextChange;
    boolean weldNumberTextChange;
    boolean frameStyleTextChange;
    boolean userRobotNumberChange;
    boolean dateChosenChange;
    boolean shiftChosenChange;
    boolean reteachMethodChange;
    boolean reasonForReteachChange;
    String userWeldNumber;
    String userCellName;
    String robotNumber;
    String userFrameStyle;
    String newDateChosen;
    String newShiftChosen;
    String reasonRetaught;
    String reteachChange;
    WeldNumber foundWeld = new WeldNumber();

    public String getUserCellName() {
        return userCellName;
    }

    public String getRobotNumber() {
        return robotNumber;
    }
    /**
     * Creates new form AppOpen
     */
    public AppOpen() {
        initComponents();
        mainPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainMenuPanel = new javax.swing.JLayeredPane();
        mainMenuCellNameLable = new javax.swing.JLabel();
        mainMenuWeldNumLabel = new javax.swing.JLabel();
        userEntryWeldNum = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        frameStyleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userPickCellName = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        userPickFrameStyle = new javax.swing.JList<>();
        searchResultsPanel = new javax.swing.JPanel();
        cellNameLabel = new javax.swing.JLabel();
        weldNumLabel = new javax.swing.JLabel();
        robotNumberLabel = new javax.swing.JLabel();
        frameStyleLabelSRLabel = new javax.swing.JLabel();
        timesRetaughtLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        weldResultsTable = new javax.swing.JTable();
        addReteachDatePicker = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        shiftChosen = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        reasonForReteach = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        reteachMethodList = new javax.swing.JList<>();
        addReteachButton = new javax.swing.JButton();
        addReteachPanel = new javax.swing.JPanel();
        weldNumLabel1 = new javax.swing.JLabel();
        cellNameLabel1 = new javax.swing.JLabel();
        frameStyleLabelAddReteach = new javax.swing.JLabel();
        newRobotFilePanel = new javax.swing.JPanel();
        mainMenuCellNameLable1 = new javax.swing.JLabel();
        mainMenuWeldNumLabel1 = new javax.swing.JLabel();
        userEntryRobotNum = new javax.swing.JTextField();
        frameStyleLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        frameStyleListFileAdd = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        cellNameListAddFile = new javax.swing.JList<>();
        newRobotFileButton = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFileMenuItem = new javax.swing.JMenuItem();
        returnToMain = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WeldTracker");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        mainMenuPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainMenuPanel.setOpaque(true);
        mainMenuPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                mainMenuPanelComponentRemoved(evt);
            }
        });

        mainMenuCellNameLable.setBackground(new java.awt.Color(0, 0, 0));
        mainMenuCellNameLable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuCellNameLable.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuCellNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuCellNameLable.setText("Cell Name:");
        mainMenuCellNameLable.setOpaque(true);

        mainMenuWeldNumLabel.setBackground(new java.awt.Color(0, 0, 0));
        mainMenuWeldNumLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuWeldNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuWeldNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuWeldNumLabel.setText("Weld #:");
        mainMenuWeldNumLabel.setOpaque(true);

        userEntryWeldNum.setBackground(new java.awt.Color(204, 204, 204));
        userEntryWeldNum.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userEntryWeldNum.setForeground(new java.awt.Color(51, 51, 51));
        userEntryWeldNum.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                userEntryWeldNumInputMethodTextChanged(evt);
            }
        });
        userEntryWeldNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEntryWeldNumActionPerformed(evt);
            }
        });

        searchButton1.setBackground(new java.awt.Color(51, 51, 51));
        searchButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchButton1.setText("Search");
        searchButton1.setBorderPainted(false);
        searchButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                searchButton1ComponentHidden(evt);
            }
        });
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               searchButton1ActionPerformed(evt);                           
                
            }
        });

        frameStyleLabel.setBackground(new java.awt.Color(0, 0, 0));
        frameStyleLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        frameStyleLabel.setForeground(new java.awt.Color(255, 255, 255));
        frameStyleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frameStyleLabel.setText("Frame Style:");
        frameStyleLabel.setOpaque(true);

        userPickCellName.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "500 R1B-1", "500 R1B-2", "500 R1B-3", "500 R2C-1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userPickCellName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                userPickCellNameInputMethodTextChanged(evt);
            }
        });

        userPickCellName.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userPickCellNameValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(userPickCellName);

        userPickFrameStyle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userPickFrameStyleValueChanged(evt);
            }
        });

        jScrollPane3.setViewportView(userPickFrameStyle);

        mainMenuPanel.setLayer(mainMenuCellNameLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(mainMenuWeldNumLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(userEntryWeldNum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(searchButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(frameStyleLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGap(0, 193, Short.MAX_VALUE)
                        .addComponent(searchButton1)
                        .addGap(410, 410, 410))
                    .addGroup(mainMenuPanelLayout.createSequentialGroup()
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainMenuCellNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frameStyleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenuWeldNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addComponent(userEntryWeldNum))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenuCellNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frameStyleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuWeldNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userEntryWeldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        mainPanel.add(mainMenuPanel, "card2");

        searchResultsPanel.setBackground(new java.awt.Color(0, 0, 0));

        cellNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        cellNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cellNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        cellNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellNameLabel.setText("R2C-3");

        weldNumLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        weldNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        weldNumLabel.setText("Weld 34");

        robotNumberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        robotNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        robotNumberLabel.setText("RB 1");

        frameStyleLabelSRLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        frameStyleLabelSRLabel.setForeground(new java.awt.Color(255, 255, 255));
        frameStyleLabelSRLabel.setText("LH Captain");

        timesRetaughtLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        timesRetaughtLabel.setForeground(new java.awt.Color(255, 255, 255));
        timesRetaughtLabel.setText("70");

        weldResultsTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        weldResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Shift", "Reason", "Change"
            }
        ));
        jScrollPane6.setViewportView(weldResultsTable);

        addReteachDatePicker.setBackground(new java.awt.Color(255, 255, 255));
        addReteachDatePicker.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                addReteachDatePickerInputMethodTextChanged(evt);
            }
        });

        shiftChosen.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        shiftChosen.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Blue", "Gold" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        shiftChosen.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                shiftChosenInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(shiftChosen);

        reasonForReteach.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reasonForReteach.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Penetration", "Undercut", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        reasonForReteach.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                reasonForReteachInputMethodTextChanged(evt);
            }
        });
        jScrollPane7.setViewportView(reasonForReteach);

        reteachMethodList.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        reteachMethodList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Shifted Weld", "Raised Weld Speed", "Lowered Weld Speed", "Retaught Point" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        reteachMethodList.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                reteachMethodListInputMethodTextChanged(evt);
            }
        });
        jScrollPane8.setViewportView(reteachMethodList);

        addReteachButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        addReteachButton.setText("Add New Reteach\n");
        addReteachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReteachButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchResultsPanelLayout = new javax.swing.GroupLayout(searchResultsPanel);
        searchResultsPanel.setLayout(searchResultsPanelLayout);
        searchResultsPanelLayout.setHorizontalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(searchResultsPanelLayout.createSequentialGroup()
                        .addComponent(addReteachDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addReteachButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchResultsPanelLayout.createSequentialGroup()
                        .addComponent(cellNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weldNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(robotNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frameStyleLabelSRLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timesRetaughtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        searchResultsPanelLayout.setVerticalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cellNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(weldNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(robotNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frameStyleLabelSRLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timesRetaughtLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addReteachButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(addReteachDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        mainPanel.add(searchResultsPanel, "card3");

        addReteachPanel.setBackground(new java.awt.Color(0, 0, 0));

        weldNumLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        weldNumLabel1.setForeground(new java.awt.Color(255, 255, 255));
        weldNumLabel1.setText("Weld 34");

        cellNameLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cellNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cellNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellNameLabel1.setText("R2C-3");

        frameStyleLabelAddReteach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        frameStyleLabelAddReteach.setForeground(new java.awt.Color(255, 255, 255));
        frameStyleLabelAddReteach.setText("LH Captain");

        javax.swing.GroupLayout addReteachPanelLayout = new javax.swing.GroupLayout(addReteachPanel);
        addReteachPanel.setLayout(addReteachPanelLayout);
        addReteachPanelLayout.setHorizontalGroup(
            addReteachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addReteachPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(cellNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weldNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frameStyleLabelAddReteach, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        addReteachPanelLayout.setVerticalGroup(
            addReteachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addReteachPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(addReteachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cellNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addReteachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weldNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(frameStyleLabelAddReteach, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(494, Short.MAX_VALUE))
        );

        mainPanel.add(addReteachPanel, "card4");

        newRobotFilePanel.setBackground(new java.awt.Color(0, 0, 0));

        mainMenuCellNameLable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuCellNameLable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuCellNameLable1.setText("Cell Name:");

        mainMenuWeldNumLabel1.setBackground(new java.awt.Color(51, 51, 51));
        mainMenuWeldNumLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuWeldNumLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuWeldNumLabel1.setText("Robot #");

        userEntryRobotNum.setBackground(new java.awt.Color(204, 204, 204));
        userEntryRobotNum.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userEntryRobotNum.setForeground(new java.awt.Color(51, 51, 51));
        userEntryRobotNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEntryRobotNumActionPerformed(evt);
            }
        });

        frameStyleLabel2.setBackground(new java.awt.Color(51, 51, 51));
        frameStyleLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        frameStyleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        frameStyleLabel2.setText("Frame Style");

        frameStyleListFileAdd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        frameStyleListFileAdd.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(frameStyleListFileAdd);

        cellNameListAddFile.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cellNameListAddFile.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "500 R1B-1", "500 R1B-2", "500 R1B-3", "500 R1C-1", "500 R1C-2", "500 R1C-3", "500 R1C-4", "500 R1C-5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        cellNameListAddFile.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cellNameListAddFileValueChanged(evt);
            }
        });

        jScrollPane5.setViewportView(cellNameListAddFile);

        newRobotFileButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newRobotFileButton.setText("Choose File");
        newRobotFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRobotFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newRobotFilePanelLayout = new javax.swing.GroupLayout(newRobotFilePanel);
        newRobotFilePanel.setLayout(newRobotFilePanelLayout);
        newRobotFilePanelLayout.setHorizontalGroup(
            newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newRobotFilePanelLayout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newRobotFilePanelLayout.createSequentialGroup()
                        .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(frameStyleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainMenuWeldNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98)
                        .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4)
                            .addComponent(userEntryRobotNum)
                            .addComponent(newRobotFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addComponent(mainMenuCellNameLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(306, 306, 306))
        );
        newRobotFilePanelLayout.setVerticalGroup(
            newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newRobotFilePanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(mainMenuCellNameLable1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(frameStyleLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuWeldNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userEntryRobotNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(newRobotFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        mainPanel.add(newRobotFilePanel, "card5");

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jFileChooser1ActionPerformed(evt);
                } catch (Exception IOException ) {
                    // TODO Auto-generated catch block
                }
            }
        });
        mainPanel.add(jFileChooser1, "card7");

        jMenu1.setText("File");

        loadFileMenuItem.setText("Load New Robot File");
        loadFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loadFileMenuItem);

        returnToMain.setText("Main Menu");
        returnToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMainActionPerformed(evt);
            }
        });
        jMenu1.add(returnToMain);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void mainMenuPanelComponentRemoved(java.awt.event.ContainerEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void searchButton1ComponentHidden(java.awt.event.ComponentEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    public void searchButton1ActionPerformed(java.awt.event.ActionEvent evt){                                              
        // TODO add your handling code here:
        if (userEntryWeldNum.getText() != null){
            weldNumberTextChange = true;
        }
        else weldNumberTextChange = false;

        if (cellNameTextChange == true && weldNumberTextChange == true){                        
            userWeldNumber = userEntryWeldNum.getText();
            userCellName = userPickCellName.getSelectedValue();
            userFrameStyle = userPickFrameStyle.getSelectedValue();
            WeldNumber foundWeld = DataSaver.supplyRetrieveSave(userCellName, userWeldNumber, userFrameStyle);            
            cellNameLabel.setText(userCellName);
            weldNumLabel.setText(userWeldNumber);
            frameStyleLabelSRLabel.setText(userFrameStyle);
            Integer arraySize = foundWeld.getDatesTimes().size();
            timesRetaughtLabel.setText(arraySize.toString());
            robotNumberLabel.setText(robotNumber);
            
            DefaultTableModel model = (DefaultTableModel) weldResultsTable.getModel();
            String [] reteach = new String [4];
            for (int i=0; i<foundWeld.getDatesTimes().size(); i++) {
                reteach [0] = foundWeld.datesTimesRetaught.get(i);
                reteach [1] = foundWeld.shiftRetaught.get(i);
                reteach [2] = foundWeld.reasonRetaught.get(i);
                reteach [3] = foundWeld.reteachMethod.get(i);
                model.addRow(reteach);
            }
            Date date = new Date();
            addReteachDatePicker.setDate(date);
            
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
        }    
        
        
        
        
    }                                             

    private void userEntryWeldNumInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                        
        // TODO add your handling code here:
        
    }

    private void loadFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card5");
        
    }                                                

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {                                              
           // TODO add your handling code here:
           File file = jFileChooser1.getSelectedFile();
           HashMap <String, WeldNumber> newMap = LineReader.readLineBR(file.getAbsolutePath(),robotNumber);
           //first calls the readLineBR method to load the contents of the file into a HashMap
           for (int i=0; i<newMap.size(); i++){
            Collection <WeldNumber> addWelds = newMap.values();
            Iterator <WeldNumber> it = addWelds.iterator();
            WeldNumber weldToBeAdded = new WeldNumber();
            while (it.hasNext()){
                weldToBeAdded =  it.next();
                DataSaver.fileMaker(robotNumber, userCellName, weldToBeAdded.getWeldNum(),userFrameStyle);
                DataSaver.serializerSave(weldToBeAdded);
            }            
           }                    
           CardLayout card = (CardLayout)mainPanel.getLayout();
           card.show(mainPanel, "card5");		
		
    }                                             

    private void returnToMainActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card2");
    }                                            

    private void userEntryWeldNumActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void userPickCellNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                        
        // TODO add your handling code here:
        
    }                                                       

    private void userEntryRobotNumActionPerformed(java.awt.event.ActionEvent evt) {                                                  
           // TODO add your handling code here:
           if (!userEntryRobotNum.getText().equals(""))userRobotNumberChange = true;
           else {
               userRobotNumberChange = false;
        }
    }                                                 

    private void newRobotFileButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        userCellName = cellNameListAddFile.getSelectedValue();
        userFrameStyle = frameStyleListFileAdd.getSelectedValue();
        robotNumber = userEntryRobotNum.getText();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel,"card7"); 
        
    }                                                  

    private void addReteachDatePickerInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                            
        // TODO add your handling code here:
        newDateChosen = addReteachDatePicker.getDateFormatString();
        dateChosenChange = true;
    }                                                           

    private void shiftChosenInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                   
        // TODO add your handling code here:
        newShiftChosen = shiftChosen.getSelectedValue();
        shiftChosenChange = true;
    }                                                  

    private void addReteachButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        if (shiftChosenChange == true && dateChosenChange == true && reasonForReteachChange == true
                &&reteachMethodChange ==true){
            newDateChosen = addReteachDatePicker.getDateFormatString();
            newShiftChosen = shiftChosen.getSelectedValue();
            reasonRetaught = reasonForReteach.getSelectedValue();
            reteachChange = reteachMethodList.getSelectedValue();
            
            foundWeld.addDateTime(newDateChosen);
            foundWeld.addShift(newShiftChosen);
            foundWeld.addReason(reasonRetaught);
            foundWeld.addModification(reteachChange);
            
            DefaultTableModel model = (DefaultTableModel) weldResultsTable.getModel();
            String [] reteach = new String [4];
            for (int i=0; i<foundWeld.getDatesTimes().size(); i++) {
                reteach [0] = foundWeld.datesTimesRetaught.get(i);
                reteach [1] = foundWeld.shiftRetaught.get(i);
                reteach [2] = foundWeld.reasonRetaught.get(i);
                reteach [3] = foundWeld.reteachMethod.get(i);
                model.addRow(reteach);
            }
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
        }
            
    }                                                

    private void reasonForReteachInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                        
        // TODO add your handling code here:
        reasonForReteachChange = true;
    }                                                       

    private void reteachMethodListInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                         
        // TODO add your handling code here:
        reteachMethodChange = true;
    }
    
    private void userPickCellNameValueChanged(javax.swing.event.ListSelectionEvent evt) {                                              
        // TODO add your handling code here:
        cellNameTextChange = true;
        if (userPickCellName.getSelectedValue().equals("500 R1B-1")
                ||userPickCellName.getSelectedValue().equals("500 R1B-2")
                ||userPickCellName.getSelectedValue().equals("500 R1B-3")
                ){
            String [] frameStyles = new String [4];
            frameStyles [0] = "LH Captain";
            frameStyles [1] = "RH Captain";
            frameStyles [2] = "LH 60% Bench";
            frameStyles [3] = "RH 40% Bench";
            
            DefaultListModel <String> listModel = new DefaultListModel<String>();
            for (String frameStyle : frameStyles) {
                listModel.addElement(frameStyle);
            }
            userPickFrameStyle.setModel(listModel);
        }
        else if(userPickCellName.getSelectedValue().equals("500 R2C-1")
                ||userPickCellName.getSelectedValue().equals("500 R2C-2")
                ||userPickCellName.getSelectedValue().equals("500 R2C-3")
                ||userPickCellName.getSelectedValue().equals("500 R2C-4")
                ||userPickCellName.getSelectedValue().equals("500 R2C-5")
                ){
            String [] frameStyles = new String [2];
            frameStyles [0] = "60% Bench";
            frameStyles [1] = "40% Bench";
            
            DefaultListModel <String> listModel = new DefaultListModel<String>();
            for (String frameStyle : frameStyles) {
                listModel.addElement(frameStyle);
            }
            userPickFrameStyle.setModel(listModel);
        }
        else {
            String [] frameStyles = new String [4];
            frameStyles [0] = "LH Captain";
            frameStyles [1] = "RH Captain";
            frameStyles [2] = "LH 60% Bench";
            frameStyles [3] = "RH 40% Bench";
            DefaultListModel <String> listModel = new DefaultListModel<String>();
            for (String frameStyle : frameStyles) {
                listModel.addElement(frameStyle);
            }
            userPickFrameStyle.setModel(listModel);
        }
    }
    
    private void cellNameListAddFileValueChanged(javax.swing.event.ListSelectionEvent evt) {                                                 
        // TODO add your handling code here:
        cellNameTextChange = true;
        if (cellNameListAddFile.getSelectedValue().equals("500 R1B-1")
                ||userPickCellName.getSelectedValue().equals("500 R1B-2")
                ||userPickCellName.getSelectedValue().equals("500 R1B-3")
                ){
            String [] frameStyles = new String [4];
            frameStyles [0] = "LH Captain";
            frameStyles [1] = "RH Captain";
            frameStyles [2] = "LH 60% Bench";
            frameStyles [3] = "RH 40% Bench";
            
            DefaultListModel <String> listModel = new DefaultListModel<String>();
            for (String frameStyle : frameStyles) {
                listModel.addElement(frameStyle);
            }
            frameStyleListFileAdd.setModel(listModel);
        }
        else if(cellNameListAddFile.getSelectedValue().equals("500 R2C-1")
                ||userPickCellName.getSelectedValue().equals("500 R2C-2")
                ||userPickCellName.getSelectedValue().equals("500 R2C-3")
                ||userPickCellName.getSelectedValue().equals("500 R2C-4")
                ||userPickCellName.getSelectedValue().equals("500 R2C-5")
                ){
            String [] frameStyles = new String [2];
            frameStyles [0] = "60% Bench";
            frameStyles [1] = "40% Bench";
            
            DefaultListModel <String> listModel = new DefaultListModel<String>();
            for (String frameStyle : frameStyles) {
                listModel.addElement(frameStyle);
            }
            frameStyleListFileAdd.setModel(listModel);
        }
        else {
            String [] frameStyles = new String [4];
            frameStyles [0] = "LH Captain";
            frameStyles [1] = "RH Captain";
            frameStyles [2] = "LH 60% Bench";
            frameStyles [3] = "RH 40% Bench";
            DefaultListModel <String> listModel = new DefaultListModel<String>();
            for (String frameStyle : frameStyles) {
                listModel.addElement(frameStyle);
            }
            frameStyleListFileAdd.setModel(listModel);
        }
    }

    private void userPickFrameStyleValueChanged(javax.swing.event.ListSelectionEvent evt) {                                                
        // TODO add your handling code here:
        frameStyleTextChange = true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppOpen().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addReteachButton;
    private com.toedter.calendar.JDateChooser addReteachDatePicker;
    private javax.swing.JPanel addReteachPanel;
    private javax.swing.JLabel cellNameLabel;
    private javax.swing.JLabel cellNameLabel1;
    private javax.swing.JList<String> cellNameListAddFile;
    private javax.swing.JLabel frameStyleLabel;
    private javax.swing.JLabel frameStyleLabel2;
    private javax.swing.JLabel frameStyleLabelAddReteach;
    private javax.swing.JLabel frameStyleLabelSRLabel;
    private javax.swing.JList<String> frameStyleListFileAdd;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JMenuItem loadFileMenuItem;
    private javax.swing.JLabel mainMenuCellNameLable;
    private javax.swing.JLabel mainMenuCellNameLable1;
    private javax.swing.JLayeredPane mainMenuPanel;
    private javax.swing.JLabel mainMenuWeldNumLabel;
    private javax.swing.JLabel mainMenuWeldNumLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton newRobotFileButton;
    private javax.swing.JPanel newRobotFilePanel;
    private javax.swing.JList<String> reasonForReteach;
    private javax.swing.JList<String> reteachMethodList;
    private javax.swing.JMenuItem returnToMain;
    private javax.swing.JLabel robotNumberLabel;
    private javax.swing.JButton searchButton1;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JList<String> shiftChosen;
    private javax.swing.JLabel timesRetaughtLabel;
    private javax.swing.JTextField userEntryRobotNum;
    private javax.swing.JTextField userEntryWeldNum;
    private javax.swing.JList<String> userPickCellName;
    private javax.swing.JList<String> userPickFrameStyle;
    private javax.swing.JLabel weldNumLabel;
    private javax.swing.JLabel weldNumLabel1;
    private javax.swing.JTable weldResultsTable;
    // End of variables declaration                   
}
