/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//package GUIPractice;

import java.awt.CardLayout;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import java.io.*;
//import java.time.temporal.WeekFields;
import java.util.*;

/**
 *
 * @author aburd
 */
public class AppOpen extends javax.swing.JFrame {

    boolean cellNameTextChange;
    String userWeldNumber;
    String userCellName;
    String robotNumber;
    

    public String getUserCellName() {
        return userCellName;
    }

    public String getRobotNumber() {
        return robotNumber;
    }
    /**
     * Creates new form AppOpen
     */
    public AppOpen() {
        initComponents();
        mainPanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainMenuPanel = new javax.swing.JLayeredPane();
        userEntryCellName = new javax.swing.JTextField();
        mainMenuCellNameLable = new javax.swing.JLabel();
        mainMenuWeldNumLabel = new javax.swing.JLabel();
        userEntryWeldNum = new javax.swing.JTextField();
        addReteachButton = new javax.swing.JButton();
        searchButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchResultsPanel = new javax.swing.JPanel();
        cellNameLabel = new javax.swing.JLabel();
        weldNumLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weldResultsTable = new javax.swing.JTable();
        addReteachPanel = new javax.swing.JPanel();
        weldNumLabel1 = new javax.swing.JLabel();
        cellNameLabel1 = new javax.swing.JLabel();
        newRobotFilePanel = new javax.swing.JPanel();
        mainMenuCellNameLable1 = new javax.swing.JLabel();
        userEntryCellName1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mainMenuWeldNumLabel1 = new javax.swing.JLabel();
        userEntryWeldNum1 = new javax.swing.JTextField();
        addFileUserQuery = new javax.swing.JPanel();
        newFileCellName = new javax.swing.JLabel();
        newFileRobotNum = new javax.swing.JLabel();
        cellNameForFile = new javax.swing.JTextField();
        robotNumForFile = new javax.swing.JTextField();
        okButtonNewFile = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadFileMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WeldTracker");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        mainMenuPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainMenuPanel.setOpaque(true);
        mainMenuPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                mainMenuPanelComponentRemoved(evt);
            }
        });

        userEntryCellName.setBackground(new java.awt.Color(204, 204, 204));
        userEntryCellName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userEntryCellName.setForeground(new java.awt.Color(51, 51, 51));
        userEntryCellName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                userEntryCellNameInputMethodTextChanged(evt);
            }
        });

        mainMenuCellNameLable.setBackground(new java.awt.Color(0, 0, 0));
        mainMenuCellNameLable.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuCellNameLable.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuCellNameLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuCellNameLable.setText("Cell Name:");
        mainMenuCellNameLable.setOpaque(true);

        mainMenuWeldNumLabel.setBackground(new java.awt.Color(0, 0, 0));
        mainMenuWeldNumLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuWeldNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainMenuWeldNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuWeldNumLabel.setText("Weld #:");
        mainMenuWeldNumLabel.setOpaque(true);

        userEntryWeldNum.setBackground(new java.awt.Color(204, 204, 204));
        userEntryWeldNum.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userEntryWeldNum.setForeground(new java.awt.Color(51, 51, 51));

        addReteachButton.setBackground(new java.awt.Color(51, 51, 51));
        addReteachButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addReteachButton.setText("Add Reteach");
        addReteachButton.setActionCommand("Add Reteach");
        addReteachButton.setBorderPainted(false);
        addReteachButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                addReteachButtonComponentHidden(evt);
            }
        });
        addReteachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReteachButtonActionPerformed(evt);
            }
        });

        searchButton1.setBackground(new java.awt.Color(51, 51, 51));
        searchButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        searchButton1.setText("Search");
        searchButton1.setBorderPainted(false);
        searchButton1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                searchButton1ComponentHidden(evt);
            }
        });
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    searchButton1ActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ex: \"500 R2C-1\"");

        mainMenuPanel.setLayer(userEntryCellName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(mainMenuCellNameLable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(mainMenuWeldNumLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(userEntryWeldNum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(addReteachButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(searchButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        mainMenuPanel.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainMenuPanelLayout = new javax.swing.GroupLayout(mainMenuPanel);
        mainMenuPanel.setLayout(mainMenuPanelLayout);
        mainMenuPanelLayout.setHorizontalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addReteachButton)
                .addGap(262, 262, 262))
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(mainMenuPanelLayout.createSequentialGroup()
                            .addComponent(mainMenuCellNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addGap(59, 59, 59)
                            .addComponent(userEntryCellName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainMenuPanelLayout.createSequentialGroup()
                            .addComponent(mainMenuWeldNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(userEntryWeldNum)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        mainMenuPanelLayout.setVerticalGroup(
            mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuPanelLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenuCellNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userEntryCellName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenuWeldNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userEntryWeldNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(mainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addReteachButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        mainPanel.add(mainMenuPanel, "card2");

        searchResultsPanel.setBackground(new java.awt.Color(0, 0, 0));

        cellNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        cellNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cellNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        cellNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellNameLabel.setText("R2C-3");

        weldNumLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        weldNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        weldNumLabel.setText("Weld 34");

        weldResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(weldResultsTable);

        javax.swing.GroupLayout searchResultsPanelLayout = new javax.swing.GroupLayout(searchResultsPanel);
        searchResultsPanel.setLayout(searchResultsPanelLayout);
        searchResultsPanelLayout.setHorizontalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(searchResultsPanelLayout.createSequentialGroup()
                        .addComponent(cellNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weldNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        searchResultsPanelLayout.setVerticalGroup(
            searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(searchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cellNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(weldNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        mainPanel.add(searchResultsPanel, "card3");

        addReteachPanel.setBackground(new java.awt.Color(0, 0, 0));

        weldNumLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        weldNumLabel1.setForeground(new java.awt.Color(255, 255, 255));
        weldNumLabel1.setText("Weld 34");

        cellNameLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cellNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        cellNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellNameLabel1.setText("R2C-3");

        javax.swing.GroupLayout addReteachPanelLayout = new javax.swing.GroupLayout(addReteachPanel);
        addReteachPanel.setLayout(addReteachPanelLayout);
        addReteachPanelLayout.setHorizontalGroup(
            addReteachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addReteachPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(cellNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weldNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(709, Short.MAX_VALUE))
        );
        addReteachPanelLayout.setVerticalGroup(
            addReteachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addReteachPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(addReteachPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cellNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(weldNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );

        mainPanel.add(addReteachPanel, "card4");

        newRobotFilePanel.setBackground(new java.awt.Color(0, 0, 0));

        mainMenuCellNameLable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuCellNameLable1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuCellNameLable1.setText("Cell Name:");

        userEntryCellName1.setBackground(new java.awt.Color(204, 204, 204));
        userEntryCellName1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userEntryCellName1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ex: \"500 R2C-1\"");

        mainMenuWeldNumLabel1.setBackground(new java.awt.Color(51, 51, 51));
        mainMenuWeldNumLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mainMenuWeldNumLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuWeldNumLabel1.setText("Robot #");

        userEntryWeldNum1.setBackground(new java.awt.Color(204, 204, 204));
        userEntryWeldNum1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        userEntryWeldNum1.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout newRobotFilePanelLayout = new javax.swing.GroupLayout(newRobotFilePanel);
        newRobotFilePanel.setLayout(newRobotFilePanelLayout);
        newRobotFilePanelLayout.setHorizontalGroup(
            newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newRobotFilePanelLayout.createSequentialGroup()
                .addContainerGap(283, Short.MAX_VALUE)
                .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newRobotFilePanelLayout.createSequentialGroup()
                        .addComponent(mainMenuCellNameLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(userEntryCellName1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newRobotFilePanelLayout.createSequentialGroup()
                        .addComponent(mainMenuWeldNumLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(userEntryWeldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(267, 267, 267))
        );
        newRobotFilePanelLayout.setVerticalGroup(
            newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newRobotFilePanelLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenuCellNameLable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userEntryCellName1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(newRobotFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenuWeldNumLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userEntryWeldNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        mainPanel.add(newRobotFilePanel, "card5");

        addFileUserQuery.setBackground(new java.awt.Color(0, 0, 0));

        newFileCellName.setBackground(new java.awt.Color(0, 0, 0));
        newFileCellName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newFileCellName.setForeground(new java.awt.Color(255, 255, 255));
        newFileCellName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newFileCellName.setText("Cell Name:");
        newFileCellName.setOpaque(true);

        newFileRobotNum.setBackground(new java.awt.Color(0, 0, 0));
        newFileRobotNum.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        newFileRobotNum.setForeground(new java.awt.Color(255, 255, 255));
        newFileRobotNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newFileRobotNum.setText("Robot Number:");
        newFileRobotNum.setOpaque(true);

        cellNameForFile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        robotNumForFile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        okButtonNewFile.setBackground(new java.awt.Color(153, 153, 153));
        okButtonNewFile.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        okButtonNewFile.setText("OK");
        okButtonNewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonNewFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addFileUserQueryLayout = new javax.swing.GroupLayout(addFileUserQuery);
        addFileUserQuery.setLayout(addFileUserQueryLayout);
        addFileUserQueryLayout.setHorizontalGroup(
            addFileUserQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFileUserQueryLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addGroup(addFileUserQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newFileRobotNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newFileCellName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFileUserQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cellNameForFile, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robotNumForFile, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(376, 376, 376))
            .addGroup(addFileUserQueryLayout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(okButtonNewFile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addFileUserQueryLayout.setVerticalGroup(
            addFileUserQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFileUserQueryLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(addFileUserQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFileCellName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellNameForFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(addFileUserQueryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFileRobotNum, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(robotNumForFile, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(okButtonNewFile)
                .addGap(114, 114, 114))
        );

        mainPanel.add(addFileUserQuery, "card6");

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jFileChooser1ActionPerformed(evt);
                } catch (FileNotFoundException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });
        mainPanel.add(jFileChooser1, "card7");

        jMenu1.setText("File");

        loadFileMenuItem.setText("Load New Robot File");
        loadFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(loadFileMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuPanelComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_mainMenuPanelComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuPanelComponentRemoved

    private void addReteachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReteachButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addReteachButtonActionPerformed

    private void addReteachButtonComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addReteachButtonComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_addReteachButtonComponentHidden

    private void searchButton1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_searchButton1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButton1ComponentHidden

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {//GEN-FIRST:event_searchButton1ActionPerformed
        // TODO add your handling code here:
        if (cellNameTextChange == true){
            userCellName = userEntryCellName.getText();
            WeldNumber foundWeld = new WeldNumber();            
            
            userWeldNumber = userEntryWeldNum.getText();
            
            File robotFile1 = new File ("C:\\Users\\aburd\\.vscode\\Robot Weld Search\\" + userCellName + "RB1.txt");
            File robotFile2 = new File ("C:\\Users\\aburd\\.vscode\\Robot Weld Search\\" + userCellName + "RB2.txt");
            
            HashMap <String, WeldNumber> robot1Map = DataSaver.parseToMap(robotFile1);
            HashMap <String, WeldNumber> robot2Map = DataSaver.parseToMap(robotFile2);
            if (robot1Map.containsKey("C:\\Users\\aburd\\.vscode\\Robot Weld Search\\" + userCellName + "RB1.txt" + "Weld " + userWeldNumber )){
                foundWeld = robot1Map.get("C:\\Users\\aburd\\.vscode\\Robot Weld Search\\" + userCellName + "RB1.txt" + "Weld " + userWeldNumber);
            }
            else if (robot2Map.containsKey("C:\\Users\\aburd\\.vscode\\Robot Weld Search\\" + userCellName + "RB2.txt" + "Weld " + userWeldNumber )){
                foundWeld = robot2Map.get("C:\\Users\\aburd\\.vscode\\Robot Weld Search\\" + userCellName + "RB2.txt" + "Weld " + userWeldNumber);
            }
            else {
                //Add handling for weld not found
            }
            
            DefaultTableModel model = (DefaultTableModel) weldResultsTable.getModel();
            String [] reteach = new String [4];
            for (int i=0; i<foundWeld.getDatesTimes().size(); i++) {
                reteach [0] = foundWeld.datesTimesRetaught.get(i);
                reteach [1] = foundWeld.shiftRetaught.get(i);
                reteach [2] = foundWeld.reasonRetaught.get(i);
                reteach [3] = foundWeld.reteachMethod.get(i);
                model.addRow(reteach);
            }
            
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
        }
        
        
        
        
        
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void userEntryCellNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_userEntryCellNameInputMethodTextChanged
                // TODO add your handling code here:
                cellNameTextChange = true;
    }//GEN-LAST:event_userEntryCellNameInputMethodTextChanged

    private void loadFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileMenuItemActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card6");
        
    }//GEN-LAST:event_loadFileMenuItemActionPerformed

    private void okButtonNewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonNewFileActionPerformed
        // TODO add your handling code here:
        userCellName = cellNameForFile.getText();
        userCellName = userCellName.toUpperCase();
        robotNumber = robotNumForFile.getText();
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card7");
                
    }//GEN-LAST:event_okButtonNewFileActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {//GEN-FIRST:event_jFileChooser1ActionPerformed
           // TODO add your handling code here:
           File file = jFileChooser1.getSelectedFile();
                                
                
           HashMap <String, WeldNumber> newMap = LineReader.readLineBR(file.getAbsolutePath());
           //first calls the readLineBR method to load the contents of the file into a HashMap
                    
           DataSaver.fileMaker(robotNumber, userCellName);
           DataSaver.writeToFile(newMap);
					
		
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppOpen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppOpen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addFileUserQuery;
    private javax.swing.JButton addReteachButton;
    private javax.swing.JPanel addReteachPanel;
    private javax.swing.JTextField cellNameForFile;
    private javax.swing.JLabel cellNameLabel;
    private javax.swing.JLabel cellNameLabel1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem loadFileMenuItem;
    private javax.swing.JLabel mainMenuCellNameLable;
    private javax.swing.JLabel mainMenuCellNameLable1;
    private javax.swing.JLayeredPane mainMenuPanel;
    private javax.swing.JLabel mainMenuWeldNumLabel;
    private javax.swing.JLabel mainMenuWeldNumLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel newFileCellName;
    private javax.swing.JLabel newFileRobotNum;
    private javax.swing.JPanel newRobotFilePanel;
    private javax.swing.JButton okButtonNewFile;
    private javax.swing.JTextField robotNumForFile;
    private javax.swing.JButton searchButton1;
    private javax.swing.JPanel searchResultsPanel;
    private javax.swing.JTextField userEntryCellName;
    private javax.swing.JTextField userEntryCellName1;
    private javax.swing.JTextField userEntryWeldNum;
    private javax.swing.JTextField userEntryWeldNum1;
    private javax.swing.JLabel weldNumLabel;
    private javax.swing.JLabel weldNumLabel1;
    private javax.swing.JTable weldResultsTable;
    // End of variables declaration//GEN-END:variables
}
